USE [dbDetranNetAtelier]
GO

/****** Object:  Table [dbo].[Inf_InfracaoAnexo]    Script Date: 11/11/2023 13:34:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Inf_InfracaoAnexo](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AIT] [varchar](50) NOT NULL,
	[AnexoBase64] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Inf_InfracaoAnexo] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


