using System;

namespace Talonario.Api.Server.Application.Entities
{
    public class Gen_ConsultaBinco
    {
        #region Public Properties

        public string Codigo { get; set; }
        public string ConsultaHICOM { get; set; }
        public string DataInclusao { get; set; }
        public string Descricao { get; set; }
        public string DescTransacao { get; set; }
        public string destino { get; set; }
        public string Funcao { get; set; }
        public string idAcao { get; set; }
        public string IdPreTransacoes { get; set; }
        public string IdSessao { get; set; }
        public int IdTransacao { get; set; }
        public string inDescricaoTipoChave { get; set; }
        public long inNumero { get; set; }
        public int inParteConsulta { get; set; }
        public string inParteFixa { get; set; }
        public int inTipoChave { get; set; }
        public string origem { get; set; }
        public string outBloqueioCodigoOrgaoRespBloqueio { get; set; }
        public string outBloqueioDataBloqueio { get; set; }
        public string outBloqueioDataFimPenalidadeBloqueios { get; set; }
        public string outBloqueioDataInicioPenalidadeBloqueios { get; set; }
        public string outBloqueioDescricaoBloqueio { get; set; }
        public string outBloqueioDescricaoCodigoOrgaoRespBloqueio { get; set; }
        public string outBloqueioDescricaoMotivoBloqueio { get; set; }
        public string outBloqueioDescricaoRecolhimentoCNH { get; set; }
        public string outBloqueioDescricaoRequisitosLiberacao { get; set; }
        public string outBloqueioDescricaoTipoAtualizacao { get; set; }
        public string outBloqueioDescricaoTipoDecisaoBloqueio { get; set; }
        public string outBloqueioDescricaoTipoPrazo { get; set; }
        public string outBloqueioDescricaoTipoPrazoTotal { get; set; }
        public string outBloqueioDocumentoGeradorBloqueio { get; set; }
        public string outBloqueioLiberadoCodigoOrgaoRespBloqueio { get; set; }
        public string outBloqueioLiberadoCodigoOrgaoRespLibBloqueio { get; set; }
        public string outBloqueioLiberadoDataBloqueio { get; set; }
        public string outBloqueioLiberadoDataFimPenalidadeBloqueios { get; set; }
        public string outBloqueioLiberadoDataInicioPenalidadeBloqueios { get; set; }
        public string outBloqueioLiberadoDataLiberacaoBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoCodigoOrgaoRespBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoCodigoOrgaoRespLibBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoMotivoBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoMotivoLiberacaoBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoRecolhimentoCNH { get; set; }
        public string outBloqueioLiberadoDescricaoRequisitosLiberacao { get; set; }
        public string outBloqueioLiberadoDescricaoTipoAtualizacao { get; set; }
        public string outBloqueioLiberadoDescricaoTipoDecisaoBloqueio { get; set; }
        public string outBloqueioLiberadoDescricaoTipoPrazo { get; set; }
        public string outBloqueioLiberadoDescricaoTipoPrazoTotal { get; set; }
        public string outBloqueioLiberadoDocumentoGeradorBloqueio { get; set; }
        public string outBloqueioLiberadoDocumentoGeradorLiberacaoBloqueio { get; set; }
        public string outBloqueioLiberadoMotivoBloqueio { get; set; }
        public string outBloqueioLiberadoMotivoLiberacaoBloqueio { get; set; }
        public string outBloqueioLiberadoPrazoPenalidade { get; set; }
        public string outBloqueioLiberadoPrazoPenalidadeTotal { get; set; }
        public string outBloqueioLiberadoRecolhimentoCNH { get; set; }
        public string outBloqueioLiberadoRequisitosLiberacao { get; set; }
        public string outBloqueioLiberadoTipoAtualizacao { get; set; }
        public string outBloqueioLiberadoTipoDecisaoBloqueio { get; set; }
        public string outBloqueioLiberadoTipoPrazo { get; set; }
        public string outBloqueioLiberadoTipoPrazoTotal { get; set; }
        public string outBloqueioLiberadoUFDetranBloqueio { get; set; }
        public string outBloqueioLiberadoUFDetranLiberacaoBloqueio { get; set; }
        public string outBloqueioMotivoBloqueio { get; set; }
        public string outBloqueioPrazoPenalidade { get; set; }
        public string outBloqueioPrazoPenalidadeTotal { get; set; }
        public string outBloqueioRecolhimentoCNH { get; set; }
        public string outBloqueioRequisitosLiberacao { get; set; }
        public string outBloqueioTipoAtualizacao { get; set; }
        public string outBloqueioTipoDecisaoBloqueio { get; set; }
        public string outBloqueioTipoPrazo { get; set; }
        public string outBloqueioTipoPrazoTotal { get; set; }
        public string outBloqueioUFDetranBloqueio { get; set; }
        public string outCancelamento { get; set; }
        public string outCategoriaAtual { get; set; }
        public string outCategoriaAutorizada { get; set; }
        public string outCategoriaRebaixada { get; set; }
        public string outCNPJLaboratorio { get; set; }
        public int outCodigoRetorno { get; set; }
        public int outCodigoTransacao { get; set; }
        public string outCodTransacaoUltimaAtualizacao { get; set; }
        public string outCPF { get; set; }
        public string outCursoCargaHoraria { get; set; }
        public string outCursoCategoria { get; set; }
        public string outCursoCNPJEntidadeCrede { get; set; }
        public string outCursoCodigoCurso { get; set; }
        public string outCursoCPFInstrutor { get; set; }
        public string outCursoDataFimCurso { get; set; }
        public string outCursoDataInicioCurso { get; set; }
        public string outCursoDataValidade { get; set; }
        public string outCursoDescricaoCodigoCurso { get; set; }
        public string outCursoDescricaoModalidade { get; set; }
        public string outCursoDescricaoMunicipioCurso { get; set; }
        public string outCursoDescricaoTipoAtualizacao { get; set; }
        public string outCursoModalidade { get; set; }
        public string outCursoMunicipioCurso { get; set; }
        public string outCursoNumeroCertificado { get; set; }
        public string outCursoObservacoes { get; set; }
        public string outCursoTipoAtualizacao { get; set; }
        public string outCursoUFCurso { get; set; }
        public string outDataCadastramento { get; set; }
        public string outDataColetaNovoExame { get; set; }
        public string outDataColetaTox { get; set; }
        public string outDataInclusaoTransacao { get; set; }
        public string outDataInicioCategoriaA { get; set; }
        public string outDataInicioCategoriaB { get; set; }
        public string outDataInicioCategoriaC { get; set; }
        public string outDataInicioCategoriaD { get; set; }
        public string outDataInicioCategoriaE { get; set; }
        public string outDataInicioCategoriaX { get; set; }
        public DateTime outDataNascimento { get; set; }
        public string outDataUltimaEmissaoHistorico { get; set; }
        public DateTime outDataValidade { get; set; }
        public string outDataValidadeTox { get; set; }
        public string outDDD { get; set; }
        public string outDescricaoCancelamento { get; set; }
        public string outDescricaoDocumentoIdentidadeTipo { get; set; }
        public string outDescricaoEnderecoMunicipio { get; set; }
        public string outDescricaoLocalidadeNascimento { get; set; }
        public string outDescricaoMotivoRequerimento1 { get; set; }
        public string outDescricaoMotivoRequerimento2 { get; set; }
        public string outDescricaoMotivoRequerimento3 { get; set; }
        public string outDescricaoMotivoRequerimento4 { get; set; }
        public string outDescricaoNacionalidade { get; set; }
        public string outDescricaoPaisOrigemHabilitacaoEstrangeira { get; set; }
        public string outDescricaoPermissionado { get; set; }
        public string outDescricaoQuadroObservacoesCNH1 { get; set; }
        public string outDescricaoQuadroObservacoesCNH10 { get; set; }
        public string outDescricaoQuadroObservacoesCNH2 { get; set; }
        public string outDescricaoQuadroObservacoesCNH3 { get; set; }
        public string outDescricaoQuadroObservacoesCNH4 { get; set; }
        public string outDescricaoQuadroObservacoesCNH5 { get; set; }
        public string outDescricaoQuadroObservacoesCNH6 { get; set; }
        public string outDescricaoQuadroObservacoesCNH7 { get; set; }
        public string outDescricaoQuadroObservacoesCNH8 { get; set; }
        public string outDescricaoQuadroObservacoesCNH9 { get; set; }
        public string outDescricaoRetorno { get; set; }
        public string outDescricaoSexo { get; set; }
        public string outDescricaoSituacaoCNH { get; set; }
        public string outDescricaoSituacaoCNHAnterior { get; set; }
        public string outDescricaoTipoChave { get; set; }
        public string outDescricaoTipoEvento { get; set; }
        public string outDescricaoUsuarioInclusaoTransacao { get; set; }
        public string outDocumentoIdentidadeNumero { get; set; }
        public string outDocumentoIdentidadeOrgaoEmissor { get; set; }
        public string outDocumentoIdentidadeTipo { get; set; }
        public string outDocumentoIdentidadeUF { get; set; }
        public string outEmail { get; set; }
        public string outEnderecoBairro { get; set; }
        public string outEnderecoCEP { get; set; }
        public string outEnderecoComplemento { get; set; }
        public string outEnderecoLogradouro { get; set; }
        public string outEnderecoMunicipio { get; set; }
        public string outEnderecoNumero { get; set; }
        public string outEnderecoUF { get; set; }
        public string outExameCategoriaPermitida { get; set; }
        public string outExameCategoriaPretendida { get; set; }
        public string outExameCNPJEntidadeCrede { get; set; }
        public string outExameCodigoExame { get; set; }
        public string outExameCPFExaminador1 { get; set; }
        public string outExameCPFExaminador2 { get; set; }
        public string outExameDataExame { get; set; }
        public string outExameDataValidade { get; set; }
        public string outExameDescricaoCodigoExame { get; set; }
        public string outExameDescricaoMunicipioExame { get; set; }
        public string outExameDescricaoResultado { get; set; }
        public string outExameDescricaoTipoAtualizacao { get; set; }
        public string outExameMunicipioExame { get; set; }
        public string outExameObservacoes { get; set; }
        public string outExameRestricoesMTexto { get; set; }
        public string outExameResultado { get; set; }
        public string outExameTipoAtualizacao { get; set; }
        public string outExameUFExame { get; set; }
        public string outFiliacaoAfetiva1 { get; set; }
        public string outFiliacaoAfetiva2 { get; set; }
        public string outIdentificacaoHabilitacaoEstrangeira { get; set; }
        public string outInfracaoAutoInfracao { get; set; }
        public string outInfracaoCodigoInfracao { get; set; }
        public string outInfracaoCodigoOrgaoAutuador { get; set; }
        public string outInfracaoCodigoOrgaoResponsavel { get; set; }
        public string outInfracaoDataInfracao { get; set; }
        public string outInfracaoDataValidade { get; set; }
        public string outInfracaoDescricaoCodigoInfracao { get; set; }
        public string outInfracaoDescricaoCodigoOrgaoAutuador { get; set; }
        public string outInfracaoDescricaoCodigoOrgaoResponsavel { get; set; }
        public string outInfracaoDescricaoTipoAtualizacao { get; set; }
        public string outInfracaoHoraInfracao { get; set; }
        public string outInfracaoIndAdverPorExcrito { get; set; }
        public string outInfracaoLocalInfracao { get; set; }
        public string outInfracaoPlacaVeiculo { get; set; }
        public string outInfracaoSerieCodigoInfracao { get; set; }
        public string outInfracaoTipoAtualizacao { get; set; }
        public string outInfracaoUFDetranInfracao { get; set; }
        public string outInfracaoUfOrgaoAutuador { get; set; }
        public string outLocalidadeNascimento { get; set; }
        public string outMotivoRequerimento1 { get; set; }
        public string outMotivoRequerimento2 { get; set; }
        public string outMotivoRequerimento3 { get; set; }
        public string outMotivoRequerimento4 { get; set; }
        public string outNacionalidade { get; set; }
        public string outNomeCondutor { get; set; }
        public string outNomeMae { get; set; }
        public string outNomePai { get; set; }
        public string outNomeSocial { get; set; }
        public string outNumero { get; set; }
        public string outNumeroCNH { get; set; }
        public string outNumeroLaudo { get; set; }
        public string outNumeroRegistro { get; set; }
        public string outNumeroRENACH { get; set; }
        public string outOcorrenciaCodigoOrgaoRespLibOcorrencia { get; set; }
        public string outOcorrenciaCodigoOrgaoRespOcorrencia { get; set; }
        public string outOcorrenciaDataFimOcorrencia { get; set; }
        public string outOcorrenciaDataInicioOcorrencia { get; set; }
        public string outOcorrenciaDataLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaDataOcorrencia { get; set; }
        public string outOcorrenciaDescricaoCodigoOrgaoRespLibOcorrencia { get; set; }
        public string outOcorrenciaDescricaoCodigoOrgaoRespOcorrencia { get; set; }
        public string outOcorrenciaDescricaoDetranLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaDescricaoMotivoLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaDescricaoMotivoOcorrencia { get; set; }
        public string outOcorrenciaDescricaoOcorrencia { get; set; }
        public string outOcorrenciaDescricaoTipoAtualizacao { get; set; }
        public string outOcorrenciaDetranLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaDocGeradorLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaDocumentoGeradorOcorrencia { get; set; }
        public string outOcorrenciaMotivoLiberacaoOcorrencia { get; set; }
        public string outOcorrenciaMotivoOcorrencia { get; set; }
        public string outOcorrenciaTipoAtualizacao { get; set; }
        public string outOcorrenciaUFDetranOcorrencia { get; set; }
        public string outPaisOrigemHabilitacaoEstrangeira { get; set; }
        public string outParteConsultaProntuario { get; set; }
        public string outParteFixa { get; set; }
        public string outPermissionado { get; set; }
        public string outPGU { get; set; }
        public string outPrazoRealizacaoToxicologico { get; set; }
        public string outPrimeiraHabilitacaoData { get; set; }
        public string outPrimeiraHabilitacaoUF { get; set; }
        public string outProximoMotivoRequerimento { get; set; }
        public string outQtEventos { get; set; }
        public string outQtPartesConsultaProntuario { get; set; }
        public string outQuadroObservacoesCNH1 { get; set; }
        public string outQuadroObservacoesCNH10 { get; set; }
        public string outQuadroObservacoesCNH2 { get; set; }
        public string outQuadroObservacoesCNH3 { get; set; }
        public string outQuadroObservacoesCNH4 { get; set; }
        public string outQuadroObservacoesCNH5 { get; set; }
        public string outQuadroObservacoesCNH6 { get; set; }
        public string outQuadroObservacoesCNH7 { get; set; }
        public string outQuadroObservacoesCNH8 { get; set; }
        public string outQuadroObservacoesCNH9 { get; set; }
        public string outRegistroNacionalEstrangeiroNumeroRNE { get; set; }
        public string outRegistroNacionalEstrangeiroOrgaoEmissor { get; set; }
        public string outRegistroNacionalEstrangeiroUF { get; set; }
        public string outSexo { get; set; }
        public string outSituacaoCNH { get; set; }
        public string outSituacaoCNHAnterior { get; set; }
        public string outSituacaoExameTox { get; set; }
        public string outTelefone { get; set; }
        public string outTipoChave { get; set; }
        public string outTipoEvento { get; set; }
        public string outUFDominio { get; set; }
        public string outUsuarioInclusaoTransacao { get; set; }
        public string outValidadeHabilitacaoEstrangeira { get; set; }
        public string UsuarioInclusao { get; set; }

        #endregion Public Properties
    }
}